export interface IFactions {
    [key: string]: string;
    Aevum: string;
    Bachman: string;
    BitRunners: string;
    BlackHand: string;
    Blade: string;
    Chongqing: string;
    Clarke: string;
    Covenant: string;
    CyberSec: string;
    Daedalus: string;
    DarkArmy: string;
    ECorp: string;
    FourSigma: string;
    Fulcrum: string;
    Illuminati: string;
    Ishima: string;
    KuaiGong: string;
    MegaCorp: string;
    Netburners: string;
    NewTokyo: string;
    NiteSec: string;
    NWO: string;
    OmniTek: string;
    Sector12: string;
    Silhouette: string;
    SlumSnakes: string;
    Speakers: string;
    Syndicate: string;
    Tetrads: string;
    TianDiHui: string;
    Volhaven: string;
}
